version: '2.10.2'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - 8083:8083
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
  subscriber:
    image: horsemens/horsemens-pahoclient:${TAG}
    env_file:
      - env/listner.env
  thermalsensor:
    image: horsemens/horsemens-pahoclient:${TAG}
    env_file:
      - env/sensor.env


  
